### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by F-Unction** [Paisseon/Xinamine#1]
How to install Xina tweaks on Dopamine?

**Comment by Paisseon** [comment]
Xinamine just sets up the environment. To install a Xina tweak, you'll have to get one that has been repackaged on Xina (after the compatibility layer patches it). I think someone is working on a script to replicate the patching process, but idk if/when it will be finished

**Comment by F-Unction** [comment]
OK, I will wait for the script.
Thank you.
