### ISSUE TITLE
[code request] Would you please upload the source code for `layout/var/jb/usr/local/bin/Xinamine`?

### ISSUE THREAD

**Issue by Liam0205** [Paisseon/Xinamine#3]
It seems that `layout/var/jb/usr/local/bin/Xinamine` is uploaded to Git by binary, and its source code could not be found in this repository.

Would you please kindly consider to take the source code of the binary under the version control?

**Comment by Paisseon** [comment]
It's right here: https://github.com/Paisseon/Xinamine/tree/emt/Binary/Sources/Xinamine
